package Frames;

import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.ImageIcon;

/**
 *
 * @author JafetDG
 */
public class MainFrame extends javax.swing.JFrame {

    public MainFrame() {
        initComponents();
        setLocationRelativeTo(null);
        /*Al ejecutar el programa se abrirá en pantalla completa*/
        setExtendedState(MAXIMIZED_BOTH);
        /*Cambia el icono del programa*/
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/iconPelon.png")));
        
        /*Desactivación de paneles*/
        softDrinks.setVisible(false);
        snacks.setVisible(false);
        iceCream.setVisible(false);
        beef.setVisible(false);
        bread.setVisible(false);
        desserts.setVisible(false);
        staples.setVisible(false);
        fruits.setVisible(false);
        vegetables.setVisible(false);
        /*------------------------*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        containerPanel = new javax.swing.JPanel();
        topbar = new javax.swing.JPanel();
        localName = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        darkMode = new javax.swing.JLabel();
        sidebar = new javax.swing.JPanel();
        icon_img = new javax.swing.JLabel();
        Separator = new javax.swing.JSeparator();
        softDrink_img = new javax.swing.JLabel();
        Bebidas = new javax.swing.JLabel();
        snacks_img = new javax.swing.JLabel();
        Snacks = new javax.swing.JLabel();
        iceCream_img = new javax.swing.JLabel();
        Helados = new javax.swing.JLabel();
        beefs_img = new javax.swing.JLabel();
        Congelados = new javax.swing.JLabel();
        bread_img = new javax.swing.JLabel();
        Reposteria = new javax.swing.JLabel();
        candy_img = new javax.swing.JLabel();
        Confites = new javax.swing.JLabel();
        staples_img = new javax.swing.JLabel();
        Despensa = new javax.swing.JLabel();
        fruits_im = new javax.swing.JLabel();
        Frutas = new javax.swing.JLabel();
        vegetables_img = new javax.swing.JLabel();
        Verduras = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        softDrinks = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        titleSd = new javax.swing.JLabel();
        snacks = new javax.swing.JPanel();
        iceCream = new javax.swing.JPanel();
        beef = new javax.swing.JPanel();
        bread = new javax.swing.JPanel();
        desserts = new javax.swing.JPanel();
        staples = new javax.swing.JPanel();
        fruits = new javax.swing.JPanel();
        vegetables = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        containerPanel.setBackground(new java.awt.Color(51, 51, 51));

        topbar.setBackground(new java.awt.Color(255, 0, 0));
        topbar.setForeground(new java.awt.Color(204, 204, 204));

        localName.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        localName.setForeground(new java.awt.Color(255, 255, 255));
        localName.setText("Soda El Pelón De La Bajura");

        username.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        username.setText("Usuario");

        darkMode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/darkMode.png"))); // NOI18N
        darkMode.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        darkMode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                darkModeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout topbarLayout = new javax.swing.GroupLayout(topbar);
        topbar.setLayout(topbarLayout);
        topbarLayout.setHorizontalGroup(
            topbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topbarLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(localName)
                .addGap(18, 18, 18)
                .addComponent(darkMode, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 269, Short.MAX_VALUE)
                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        topbarLayout.setVerticalGroup(
            topbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topbarLayout.createSequentialGroup()
                .addGroup(topbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(localName, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addComponent(username, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(topbarLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(darkMode)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sidebar.setBackground(new java.awt.Color(131, 0, 0));

        icon_img.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconPelon2.png"))); // NOI18N

        Separator.setForeground(new java.awt.Color(255, 255, 255));

        softDrink_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/softDrink.png"))); // NOI18N

        Bebidas.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        Bebidas.setForeground(new java.awt.Color(255, 255, 255));
        Bebidas.setText("Bebidas");
        Bebidas.setToolTipText("");
        Bebidas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Bebidas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BebidasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BebidasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BebidasMouseExited(evt);
            }
        });

        snacks_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/snacks.png"))); // NOI18N

        Snacks.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        Snacks.setForeground(new java.awt.Color(255, 255, 255));
        Snacks.setText("Snacks");
        Snacks.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Snacks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SnacksMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SnacksMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SnacksMouseExited(evt);
            }
        });

        iceCream_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iceCream.png"))); // NOI18N

        Helados.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        Helados.setForeground(new java.awt.Color(255, 255, 255));
        Helados.setText("Helados");
        Helados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Helados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HeladosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HeladosMouseExited(evt);
            }
        });

        beefs_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/beefs.png"))); // NOI18N

        Congelados.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        Congelados.setForeground(new java.awt.Color(255, 255, 255));
        Congelados.setText("Congelados");
        Congelados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Congelados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CongeladosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CongeladosMouseExited(evt);
            }
        });

        bread_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bread.png"))); // NOI18N

        Reposteria.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        Reposteria.setForeground(new java.awt.Color(255, 255, 255));
        Reposteria.setText("Repostería");
        Reposteria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Reposteria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ReposteriaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ReposteriaMouseExited(evt);
            }
        });

        candy_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/candy.png"))); // NOI18N

        Confites.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        Confites.setForeground(new java.awt.Color(255, 255, 255));
        Confites.setText("Confítes");
        Confites.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Confites.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ConfitesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ConfitesMouseExited(evt);
            }
        });

        staples_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/staples.png"))); // NOI18N

        Despensa.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        Despensa.setForeground(new java.awt.Color(255, 255, 255));
        Despensa.setText("Despensa");
        Despensa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Despensa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DespensaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DespensaMouseExited(evt);
            }
        });

        fruits_im.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fruits.png"))); // NOI18N

        Frutas.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        Frutas.setForeground(new java.awt.Color(255, 255, 255));
        Frutas.setText("Frutas");
        Frutas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Frutas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FrutasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                FrutasMouseExited(evt);
            }
        });

        vegetables_img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vegetables.png"))); // NOI18N

        Verduras.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        Verduras.setForeground(new java.awt.Color(255, 255, 255));
        Verduras.setText("Verduras");
        Verduras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Verduras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VerdurasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VerdurasMouseExited(evt);
            }
        });

        javax.swing.GroupLayout sidebarLayout = new javax.swing.GroupLayout(sidebar);
        sidebar.setLayout(sidebarLayout);
        sidebarLayout.setHorizontalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidebarLayout.createSequentialGroup()
                        .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(sidebarLayout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(Separator, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(sidebarLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(icon_img, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 13, Short.MAX_VALUE))
                    .addGroup(sidebarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(sidebarLayout.createSequentialGroup()
                                .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(candy_img, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bread_img, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Reposteria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(sidebarLayout.createSequentialGroup()
                                        .addComponent(Confites)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(sidebarLayout.createSequentialGroup()
                                .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(sidebarLayout.createSequentialGroup()
                                        .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(snacks_img, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(softDrink_img))
                                            .addComponent(iceCream_img, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Bebidas)
                                            .addComponent(Snacks)
                                            .addComponent(Helados)))
                                    .addGroup(sidebarLayout.createSequentialGroup()
                                        .addComponent(beefs_img, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Congelados))
                                    .addGroup(sidebarLayout.createSequentialGroup()
                                        .addComponent(staples_img, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Despensa))
                                    .addGroup(sidebarLayout.createSequentialGroup()
                                        .addComponent(fruits_im, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Frutas))
                                    .addGroup(sidebarLayout.createSequentialGroup()
                                        .addComponent(vegetables_img, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Verduras)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        sidebarLayout.setVerticalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidebarLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(icon_img)
                .addGap(18, 18, 18)
                .addComponent(Separator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(softDrink_img, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Bebidas, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(snacks_img, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Snacks, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(iceCream_img, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Helados, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(beefs_img, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Congelados, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bread_img, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Reposteria, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(candy_img, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Confites, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(staples_img, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Despensa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fruits_im, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Frutas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(vegetables_img, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Verduras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(111, Short.MAX_VALUE))
        );

        content.setBackground(new java.awt.Color(255, 255, 255));

        softDrinks.setBackground(new java.awt.Color(255, 255, 255));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
        }

        titleSd.setFont(new java.awt.Font("Leelawadee UI", 1, 36)); // NOI18N
        titleSd.setForeground(new java.awt.Color(0, 0, 0));
        titleSd.setText("Bebidas");

        javax.swing.GroupLayout softDrinksLayout = new javax.swing.GroupLayout(softDrinks);
        softDrinks.setLayout(softDrinksLayout);
        softDrinksLayout.setHorizontalGroup(
            softDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(softDrinksLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(titleSd)
                .addGap(121, 121, 121)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
                .addContainerGap())
        );
        softDrinksLayout.setVerticalGroup(
            softDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(softDrinksLayout.createSequentialGroup()
                .addGroup(softDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(softDrinksLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(softDrinksLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(softDrinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(titleSd))))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout snacksLayout = new javax.swing.GroupLayout(snacks);
        snacks.setLayout(snacksLayout);
        snacksLayout.setHorizontalGroup(
            snacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1012, Short.MAX_VALUE)
        );
        snacksLayout.setVerticalGroup(
            snacksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 671, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout iceCreamLayout = new javax.swing.GroupLayout(iceCream);
        iceCream.setLayout(iceCreamLayout);
        iceCreamLayout.setHorizontalGroup(
            iceCreamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1012, Short.MAX_VALUE)
        );
        iceCreamLayout.setVerticalGroup(
            iceCreamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 671, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout beefLayout = new javax.swing.GroupLayout(beef);
        beef.setLayout(beefLayout);
        beefLayout.setHorizontalGroup(
            beefLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1012, Short.MAX_VALUE)
        );
        beefLayout.setVerticalGroup(
            beefLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 671, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout breadLayout = new javax.swing.GroupLayout(bread);
        bread.setLayout(breadLayout);
        breadLayout.setHorizontalGroup(
            breadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1012, Short.MAX_VALUE)
        );
        breadLayout.setVerticalGroup(
            breadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 671, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout dessertsLayout = new javax.swing.GroupLayout(desserts);
        desserts.setLayout(dessertsLayout);
        dessertsLayout.setHorizontalGroup(
            dessertsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1012, Short.MAX_VALUE)
        );
        dessertsLayout.setVerticalGroup(
            dessertsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 671, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout staplesLayout = new javax.swing.GroupLayout(staples);
        staples.setLayout(staplesLayout);
        staplesLayout.setHorizontalGroup(
            staplesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1012, Short.MAX_VALUE)
        );
        staplesLayout.setVerticalGroup(
            staplesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 671, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout fruitsLayout = new javax.swing.GroupLayout(fruits);
        fruits.setLayout(fruitsLayout);
        fruitsLayout.setHorizontalGroup(
            fruitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1012, Short.MAX_VALUE)
        );
        fruitsLayout.setVerticalGroup(
            fruitsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 671, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout vegetablesLayout = new javax.swing.GroupLayout(vegetables);
        vegetables.setLayout(vegetablesLayout);
        vegetablesLayout.setHorizontalGroup(
            vegetablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1012, Short.MAX_VALUE)
        );
        vegetablesLayout.setVerticalGroup(
            vegetablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 671, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(softDrinks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(snacks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(iceCream, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(beef, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(bread, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(desserts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(staples, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(fruits, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(vegetables, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(softDrinks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(snacks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(iceCream, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(beef, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(bread, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(desserts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(staples, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(fruits, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(vegetables, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout containerPanelLayout = new javax.swing.GroupLayout(containerPanel);
        containerPanel.setLayout(containerPanelLayout);
        containerPanelLayout.setHorizontalGroup(
            containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerPanelLayout.createSequentialGroup()
                .addComponent(sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(topbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        containerPanelLayout.setVerticalGroup(
            containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerPanelLayout.createSequentialGroup()
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerPanelLayout.createSequentialGroup()
                        .addComponent(topbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(sidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(containerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(containerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void darkModeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_darkModeMouseClicked
    /*Compara el tema en el que esté el programa, si esta en tema claro se cambia de icono a la luna, el color a oscuro y viceversa*/
        if (content.getBackground().equals(new java.awt.Color(51, 51, 51))) {
            content.setBackground(new java.awt.Color(255, 255, 255));
            ImageIcon dark = new ImageIcon("C:\\Users\\admin\\OneDrive\\Documentos\\Soda\\Soda_ElPelon\\src\\main\\resources\\darkMode.png");            
            darkMode.setIcon(dark);            
        } else if (content.getBackground().equals(new java.awt.Color(255, 255, 255))) {
            content.setBackground(new java.awt.Color(51, 51, 51));
            ImageIcon light = new ImageIcon("C:\\Users\\admin\\OneDrive\\Documentos\\Soda\\Soda_ElPelon\\src\\main\\resources\\ligthMode.png");
            darkMode.setIcon(light);
        }                             
        
        if (softDrinks.getBackground().equals(new java.awt.Color(51, 51, 51))) {
            softDrinks.setBackground(new java.awt.Color(255, 255, 255));
            ImageIcon dark = new ImageIcon("C:\\Users\\admin\\OneDrive\\Documentos\\Soda\\Soda_ElPelon\\src\\main\\resources\\darkMode.png");
            darkMode.setIcon(dark);
            titleSd.setForeground(Color.black);
        } else if (softDrinks.getBackground().equals(new java.awt.Color(255, 255, 255))) {
            softDrinks.setBackground(new java.awt.Color(51, 51, 51));
            ImageIcon light = new ImageIcon("C:\\Users\\admin\\OneDrive\\Documentos\\Soda\\Soda_ElPelon\\src\\main\\resources\\ligthMode.png");
            darkMode.setIcon(light);
            titleSd.setForeground(Color.white);
        } 
        
    }//GEN-LAST:event_darkModeMouseClicked

    /*Efectos Hover*/
    
    private void BebidasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BebidasMouseEntered
        Bebidas.setForeground(new java.awt.Color(204,204,0));
    }//GEN-LAST:event_BebidasMouseEntered

    private void BebidasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BebidasMouseExited
        Bebidas.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_BebidasMouseExited

    private void SnacksMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SnacksMouseEntered
        Snacks.setForeground(new java.awt.Color(204,204,0));
    }//GEN-LAST:event_SnacksMouseEntered

    private void SnacksMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SnacksMouseExited
        Snacks.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_SnacksMouseExited

    private void HeladosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeladosMouseEntered
        Helados.setForeground(new java.awt.Color(204,204,0));
    }//GEN-LAST:event_HeladosMouseEntered

    private void HeladosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeladosMouseExited
        Helados.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_HeladosMouseExited

    private void CongeladosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CongeladosMouseEntered
        Congelados.setForeground(new java.awt.Color(204,204,0));
    }//GEN-LAST:event_CongeladosMouseEntered

    private void CongeladosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CongeladosMouseExited
        Congelados.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_CongeladosMouseExited

    private void ReposteriaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReposteriaMouseEntered
        Reposteria.setForeground(new java.awt.Color(204,204,0));
    }//GEN-LAST:event_ReposteriaMouseEntered

    private void ReposteriaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReposteriaMouseExited
        Reposteria.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_ReposteriaMouseExited

    private void ConfitesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConfitesMouseEntered
        Confites.setForeground(new java.awt.Color(204,204,0));
    }//GEN-LAST:event_ConfitesMouseEntered

    private void ConfitesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConfitesMouseExited
        Confites.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_ConfitesMouseExited

    private void DespensaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DespensaMouseEntered
        Despensa.setForeground(new java.awt.Color(204,204,0));
    }//GEN-LAST:event_DespensaMouseEntered

    private void DespensaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DespensaMouseExited
        Despensa.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_DespensaMouseExited

    private void FrutasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FrutasMouseEntered
        Frutas.setForeground(new java.awt.Color(204,204,0));
    }//GEN-LAST:event_FrutasMouseEntered

    private void FrutasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FrutasMouseExited
        Frutas.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_FrutasMouseExited

    private void VerdurasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VerdurasMouseEntered
        Verduras.setForeground(new java.awt.Color(204,204,0));
    }//GEN-LAST:event_VerdurasMouseEntered

    private void VerdurasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VerdurasMouseExited
        Verduras.setForeground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_VerdurasMouseExited

    
    /*Activacion de paneles*/
    private void BebidasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BebidasMouseClicked
        if (!softDrinks.isVisible()) {
            softDrinks.setVisible(true);
        } else {
            if (snacks.isVisible() || iceCream.isVisible() || beef.isVisible() || bread.isVisible() || desserts.isVisible() || staples.isVisible() || fruits.isVisible() || vegetables.isVisible()) {
                softDrinks.setVisible(false);
            }
        }
        
    }//GEN-LAST:event_BebidasMouseClicked

    private void SnacksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SnacksMouseClicked
        snacks.setVisible(true);
    }//GEN-LAST:event_SnacksMouseClicked

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bebidas;
    private javax.swing.JLabel Confites;
    private javax.swing.JLabel Congelados;
    private javax.swing.JLabel Despensa;
    private javax.swing.JLabel Frutas;
    private javax.swing.JLabel Helados;
    private javax.swing.JLabel Reposteria;
    private javax.swing.JSeparator Separator;
    private javax.swing.JLabel Snacks;
    private javax.swing.JLabel Verduras;
    private javax.swing.JPanel beef;
    private javax.swing.JLabel beefs_img;
    private javax.swing.JPanel bread;
    private javax.swing.JLabel bread_img;
    private javax.swing.JLabel candy_img;
    private javax.swing.JPanel containerPanel;
    private javax.swing.JPanel content;
    private javax.swing.JLabel darkMode;
    private javax.swing.JPanel desserts;
    private javax.swing.JPanel fruits;
    private javax.swing.JLabel fruits_im;
    private javax.swing.JPanel iceCream;
    private javax.swing.JLabel iceCream_img;
    private javax.swing.JLabel icon_img;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel localName;
    private javax.swing.JPanel sidebar;
    private javax.swing.JPanel snacks;
    private javax.swing.JLabel snacks_img;
    private javax.swing.JLabel softDrink_img;
    private javax.swing.JPanel softDrinks;
    private javax.swing.JPanel staples;
    private javax.swing.JLabel staples_img;
    private javax.swing.JLabel titleSd;
    private javax.swing.JPanel topbar;
    private javax.swing.JLabel username;
    private javax.swing.JPanel vegetables;
    private javax.swing.JLabel vegetables_img;
    // End of variables declaration//GEN-END:variables
}
